name: Hello World
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
<<<<<<< HEAD
        run: docker build -t phonebook-worker .
=======
        run: echo "A demo build"
>>>>>>> parent of 9de1407 (changing the worker to make it actually do something)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test phase
<<<<<<< HEAD
        run: go test -v ./...
=======
        run: echo "Running test cases..."
>>>>>>> parent of 9de1407 (changing the worker to make it actually do something)
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the App
<<<<<<< HEAD
        run: docker run -d -p 8080:8080 phonebook-worker
=======
        run: echo "Deploying the app..."
>>>>>>> parent of 9de1407 (changing the worker to make it actually do something)
